### ISSUE TITLE
Conditional CSS preload

### ISSUE THREAD

**Issue by ggeorgovassilis** [kasparsd/code-prettify#33]
Issue #30 preloads prettify.css. This has a drawback when optimisations like the [Fast Velocity Minify plugin](https://wordpress.org/plugins/fast-velocity-minify/) are active, which bundles all CSS into a single file. In that case the preloader still fetches prittify.css issuing an unnecessary http request in every page. Preloading should be conditional on a setting.

**Comment by kasparsd** [comment]
Thanks for reporting the issue!

The `prettify.css` is loaded via JS instead of `wp_enqueue_script()` so it shouldn't be possible for concatenation plugins to include it in the bundle. I'm not seeing the issue with https://github.com/kasparsd/minit for example.

You bring up a good point, though -- that preload only makes sense when the `prettify.css` is going to be actually used. I wonder if the prettify library loads it on every page or we're triggering false preloads when the CSS file isn't actually needed.

**Comment by ggeorgovassilis** [comment]
Thank you for the quick response. I worked around the issue by commenting prettify_preload_code_styles

**Comment by kasparsd** [comment]
I just posted [an alternative solution in the wiki](https://github.com/kasparsd/code-prettify/wiki#disable-prettifycss-preload) that should allow you to keep the plugin updated and have the preload disabled.

Also, could you please confirm if and how `prettify.css` get's included in the FVM bundle even when it's added via JS? Is that because of that preload rule?

**Comment by ggeorgovassilis** [comment]
> Also, could you please confirm if and how `prettify.css` get's included in the FVM bundle even when it's added via JS? Is that because of that preload rule?

It's `<link rel="preload">`  inlined into the page's html. The FVM bundle already includes prettify.css, so removing the preloader doesn't affect functionality.

**Comment by kasparsd** [comment]
Shouldn't it remove the preload tag if it already inlined its content?
